server:
  port: ${PORT:0}

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.instance-id:${random.value}}
    # Change default status page from /actuator/status to custom endpoint
    status-page-url-path: /users/status/check
    prefer-ip-address: true

# load from config server
token:
  # 1 day
  expireTime: 8640000
  signingKey: ahihi

logging:
  level:
    com.photoapp.user.data.AlbumServiceClient: DEBUG

feign:
  client:
    config:
      default:
        logger-level: FULL


