server:
  port: ${PORT:0}

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.instance-id:${random.value}}
    status-page-url-path: /users/status/check
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      album-service:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
        minimum-number-of-calls: 1
        slow-call-duration-threshold: 200
        wait-duration-in-open-state: 10000
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true

# load from config server
token:
  # 1 day
  expireTime: 8640000
  signingKey: ahihi

logging:
  level:
    com.photoapp.user.data.AlbumServiceClient: DEBUG

feign:
  client:
    config:
      default:
        logger-level: FULL