server:
  port: 0

spring:
  application:
    name: users-service
  datasource:
    url: jdbc:mysql://localhost:3306/photo-app
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.instance-id:${random.value}}
    # Change default status page from /actuator/status to custom endpoint
    status-page-url-path: /users/status/check
    prefer-ip-address: true

# load from config server
token:
  # 1 day
  expireTime: 8640000
  signingKey: ahihi



