server:
  port: 0

spring:
  application:
    name: users-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    # To make this work with H2, we need dependency spring-boot-starter-data-jpa
    # Check: https://stackoverflow.com/questions/63587966/spring-boot-h2-database-not-found-not-created-by-liquibase
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.instance-id:${random.value}}
    # Change default status page from /actuator/status to custom endpoint
    status-page-url-path: /users/status/check
    prefer-ip-address: true

# load from config server
token:
  # 1 day
  expireTime: 8640000
  signingKey: ahihi



