server:
  port: ${PORT:0}

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      album-service:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
        minimum-number-of-calls: 1
        slow-call-duration-threshold: 1s
        wait-duration-in-open-state: 10s
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
  retry:
    retry-aspect-order: 2
    instances:
      album-service:
        max-attempts: 3
        wait-duration: 200ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

# load from config server
token:
  expireTime: 8640000
  signingKey: ahihi

logging:
  level:
    com.photoapp.user.data.AlbumServiceClient: DEBUG